### ISSUE TITLE
Not working production

### ISSUE THREAD

**Issue by elzup** [annict/dashboard#2]
止まってます
![annict_dashboard](https://cloud.githubusercontent.com/assets/2284908/23514367/784d4f3a-ffaa-11e6-8ee2-4282f968838f.png)

**Comment by shimbaco** [comment]
@elzup ご連絡ありがとうございます！ダッシュボードはもともと[Keen IO](https://keen.io/)に保存したデータを表示していたのですが、しばらくKeen IOを使っていない時期があり、そのときから今の状態になってました…。
リニューアル後からまたKeen IOを使い始めたので、気が向いたら復活させます…！ 🙇
